# 公共配置文件
spring:
  application:
    name: apidevelopment-platform
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_platform
    username: root
    password: 20020901lcb
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
  #  邮箱配置 todo 修改为自己的邮箱发送配置 password为邮箱授权码
  mail:
    # QQ邮箱的SMTP服务器地址
    host: smtp.qq.com
    username: 2500822924@qq.com
    emailFrom: 2500822924@qq.com
    # 邮箱授权码
    password: wafwvxozmyoqdjbg
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    publisher-confirm-type: correlated #开启发送端确认
    publisher-returns: true #开启发送端消息抵达队列的确认
    template:
      mandatory: true #只要抵达队列，以异步发送优先回调我们这个returnsConfirm
#    password: 123456
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  # 内网映射这个端口别写错了(内网穿透后，内网穿透地址要和这里的8101端口起同样作用,内网穿透后的地址就是公网地址)
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置  这里的密钥不能提交的git上，推送会失败
cos:
  client:
    accessKey: 1
    secretKey: 1
    region: 1
    bucket: 1
# 沙箱支付
alipay:
  # 支付宝应用ID
  appId: a
  # 应用私钥
  appPrivateKey: a
  # 应用公钥
  alipayPublicKey: a
  # 支付宝支付回调通知的地址 （这是我们后端自己提供的接口，由于需要使用公网地址这里就不使用8081，使用内网穿透地址；注意：内网穿透地址每次启动都会改变）
  notifyUrl:  a
  # 支付完成后的回调地址 (前端地址)
  returnUrl: a
  signType: RSA2
  charset: utf-8
  # 支付宝网关地址
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do


# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - api.development.platform.controller
name:  # 用户签名
  client:
    access-key: poise.admin
    secret-key: admin.admin
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: 22221
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
# 腾讯云信息
tencent:
  secretId: #你的secretId
  secretKey: #你的secretKey
  sdkAppId: #你的sdkAppId
  signName: #你的signName
  templateId: #你的templateId
