server:
  port: 8111
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
#            - Path=/api/{api_url}

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace